
model:
  # name of the NLP model that will be registered on MLFlow registry
  name: 'solacc_esg'
  spacy:
    # directory must be accessible from each executor
    # we will download latest spacy pre-trained pipeline for entity resolution
    path: '/dbfs/FileStore/solution_accelerators/esg/spacy'
  nltk:
    # directory must be accessible from each executor
    # we will download latest NLTK pre-trained pipeline for lemmatization
    path: '/dbfs/FileStore/solution_accelerators/esg/nltk'

csr:
  # how many CSR files do we want to download before saving files on a delta table
  # PDFs may be quite large, so keeping this under 100 would be ideal
  batch_size: 30
  
gdelt:
  # gdelt v2 dataset spans from 1970 to today and updated every 15mn
  raw: '/mnt/industry-gtm/fsi/datasets/gdelt_gkg_raw'
  # we recommend reading at least 2 months worth of data to capture enough news information for each company
  dir: '/mnt/industry-gtm/fsi/datasets/gdelt_gkg'
  
database:
  # all delta tables will be stored as external managed tables under that database / within that directory
  name: 'solacc_esg'
  path: '/FileStore/solution_accelerators/esg/database'
  tables:
    portfolio: 'portfolio'
    csr:
      # storing all CSR related information
      bronze: 'csr_bronze'
      silver: 'csr_silver'
      gold:   'csr_gold'
      topics: 'csr_topics'
      scores: 'csr_scores'
    gdelt:
      # storing all GDELT related information
      contributions: 'gdelt_contributions'
      bronze: 'gdelt_bronze'
      silver: 'gdelt_silver'
      scores: 'gdelt_scores'

environment:
  # in a highly distributed environment, we can further accelerate model development by specifying hyper opts number of tasks
  executors: 20